main: parser.cpp main.cpp
	g++ -std=c++11 -o main.out main.cpp parser.cpp
debug: parser.cpp main.cpp
	g++ -std=c++11 -o main.out main.cpp parser.cpp -g
generator: test_case_generator.cpp
	g++ -std=c++11 -o generator.out test_case_generator.cpp
